In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('movies.csv')
df

,rank,name,year,rating,genre,certificate,run_time,tagline,budget,box_office,casts,directors,writers
0,1,The Shawshank Redemption,1994,9.3,Drama,R,2h 22m,Fear can hold you prisoner. Hope can set you f...,25000000,28884504,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",Frank Darabont,"Stephen King,Frank Darabont"
1,2,The Godfather,1972,9.2,"Crime,Drama",R,2h 55m,An offer you can't refuse.,6000000,250341816,"Marlon Brando,Al Pacino,James Caan,Diane Keato...",Francis Ford Coppola,"Mario Puzo,Francis Ford Coppola"
2,3,The Dark Knight,2008,9.0,"Action,Crime,Drama",PG-13,2h 32m,Why So Serious?,185000000,1006234167,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",Christopher Nolan,"Jonathan Nolan,Christopher Nolan,David S. Goyer"
3,4,The Godfather Part II,1974,9.0,"Crime,Drama",R,3h 22m,All the power on earth can't change destiny.,13000000,47961919,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",Francis Ford Coppola,"Francis Ford Coppola,Mario Puzo"
4,5,12 Angry Men,1957,9.0,"Crime,Drama",Approved,1h 36m,Life Is In Their Hands -- Death Is On Their Mi...,350000,955,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",Sidney Lumet,Reginald Rose
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,The Help,2011,8.1,Drama,PG-13,2h 26m,Change begins with a whisper.,25000000,216639112,"Viola Davis,Emma Stone,Octavia Spencer,Bryce D...",Tate Taylor,"Tate Taylor,Kathryn Stockett"
246,247,Dersu Uzala,1975,8.2,"Adventure,Biography,Drama",G,2h 22m,There is man and beast at nature's mercy. Ther...,4000000,14480,"Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...",Akira Kurosawa,"Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev"
247,248,Aladdin,1992,8.0,"Animation,Adventure,Comedy",G,1h 30m,Wish granted! (DVD re-release),Not Available,Not Available,"Scott Weinger,Robin Williams,Linda Larkin,Jona...","Ron Clements,John Musker","Ron Clements,John Musker,Ted Elliott"
248,249,Gandhi,1982,8.0,"Biography,Drama,History",PG,3h 11m,His Triumph Changed The World Forever.,22000000,52767889,"Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...",Richard Attenborough,John Briley
249,250,Dances with Wolves,1990,8.0,"Adventure,Drama,Western",PG-13,3h 1m,Inside everyone is a frontier waiting to be di...,22000000,424208848,"Kevin Costner,Mary McDonnell,Graham Greene,Rod...",Kevin Costner,Michael Blake

In [3]:
column_names = df.columns
column_names

Index(['rank', 'name', 'year', 'rating', 'genre', 'certificate', 'run_time',
       'tagline', 'budget', 'box_office', 'casts', 'directors', 'writers'],
      dtype='object')

In [4]:
unique_genres = df['genre'].unique()
unique_genres

array(['Drama', 'Crime,Drama', 'Action,Crime,Drama',
       'Biography,Drama,History', 'Action,Adventure,Drama',
       'Adventure,Western', 'Drama,Romance', 'Action,Adventure,Sci-Fi',
       'Action,Adventure,Fantasy', 'Action,Sci-Fi',
       'Biography,Crime,Drama', 'Crime,Drama,Mystery', 'Action,Drama',
       'Drama,Family,Fantasy', 'Crime,Drama,Thriller', 'Drama,War',
       'Adventure,Drama,Sci-Fi', 'Comedy,Drama,Romance',
       'Crime,Drama,Fantasy', 'Adventure,Comedy,Sci-Fi',
       'Animation,Adventure,Family', 'Biography,Drama,Music',
       'Horror,Mystery,Thriller', 'Drama,Thriller',
       'Animation,Adventure,Drama', 'Drama,Mystery,Sci-Fi', 'Drama,Music',
       'Drama,Romance,War', 'Animation,Drama,War', 'Action,Drama,Mystery',
       'Biography,Comedy,Drama', 'Western', 'Mystery,Thriller',
       'Horror,Sci-Fi', 'Drama,Mystery,War', 'Drama,Western',
       'Action,Adventure', 'Drama,Mystery,Thriller', 'Drama,Film-Noir',
       'Drama,Horror', 'Comedy,Drama,War', 'Animation,Action,Adventure',
       'Comedy,War', 'Adventure,Drama,War', 'Animation,Adventure,Comedy',
       'Animation,Drama,Fantasy', 'Comedy,Drama',
       'Comedy,Musical,Romance', 'Drama,Romance,Sci-Fi',
       'Adventure,Sci-Fi', 'Crime,Thriller', 'Drama,Thriller,War',
       'Drama,Mystery', 'Crime,Mystery,Thriller',
       'Adventure,Biography,Drama', 'Action,Adventure,Mystery',
       'Mystery,Romance,Thriller', 'Comedy,Romance', 'Crime,Sci-Fi',
       'Crime,Drama,Film-Noir', 'Comedy,Crime,Drama', 'Drama,Sci-Fi',
       'Action,Thriller', 'Comedy,Crime', 'Drama,Family',
       'Action,Drama,War', 'Action,Biography,Drama',
       'Comedy,Drama,Family', 'Comedy,Music,Romance',
       'Biography,Comedy,Crime', 'Drama,Fantasy,War', 'Biography,Drama',
       'Action,Drama,Thriller', 'Adventure,Drama,Western',
       'Adventure,Comedy,Fantasy', 'Adventure,Drama,History',
       'Horror,Mystery,Sci-Fi', 'Biography,Drama,Sport',
       'Action,Drama,Sci-Fi', 'Action,Comedy,Crime',
       'Drama,Mystery,Romance', 'Action,Drama,Sport',
       'Animation,Comedy,Family', 'Drama,Sport', 'Drama,Family,Sport',
       'Adventure,Comedy,Drama', 'Adventure,Family,Fantasy',
       'Adventure,Drama', 'Adventure,Comedy,Crime',
       'Action,Adventure,Comedy', 'Film-Noir,Mystery,Thriller',
       'Adventure,Drama,Thriller', 'Action,Comedy,Romance',
       'Comedy,Drama,Thriller', 'Drama,Fantasy', 'Animation,Comedy,Drama',
       'Adventure,Thriller', 'Comedy,Drama,Fantasy', 'Horror',
       'Comedy,Romance,War', 'Biography,Drama,Family',
       'Drama,Film-Noir,Mystery', 'Drama,Romance,Thriller', 'Comedy'],
      dtype=object)

In [5]:
print(df.dtypes)

rank             int64
name            object
year             int64
rating         float64
genre           object
certificate     object
run_time        object
tagline         object
budget          object
box_office      object
casts           object
directors       object
writers         object
dtype: object

In [6]:
# extract hours and minutes of run_time
df[['Hours', 'Minutes']] = df['run_time'].str.extract(r'(?:(\d+)h)? ?(?:(\d+)m)?')

# Replace NaN with 0 and convert to integers
df['Hours'] = df['Hours'].fillna(0).astype(int)
df['Minutes'] = df['Minutes'].fillna(0).astype(int)

# compute total minutes
df['TotalMinutes'] = df['Hours'] * 60 + df['Minutes']

# compute the average 
average_run_time = df['TotalMinutes'].mean()

print(f"Average time in minutes: {average_run_time}")

Average time in minutes: 128.536